// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFNRogqOAbzRU5fd8zvOGljAziZBbsgAc',
    appId: '1:792531175929:web:b0f93334026cb5b8afd528',
    messagingSenderId: '792531175929',
    projectId: 'pmc-nt',
    authDomain: 'pmc-nt.firebaseapp.com',
    storageBucket: 'pmc-nt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9f8U0ZZpjLjfIp24LtwTcVbAgCST3IAI',
    appId: '1:792531175929:android:e3dfbac421c80dd1afd528',
    messagingSenderId: '792531175929',
    projectId: 'pmc-nt',
    storageBucket: 'pmc-nt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcqDJ_E4mJfCs4qodNei4TfmKIqx9fxA',
    appId: '1:792531175929:ios:838b8d92fad47009afd528',
    messagingSenderId: '792531175929',
    projectId: 'pmc-nt',
    storageBucket: 'pmc-nt.appspot.com',
    iosClientId: '792531175929-b984v7djph0ktd8o0nf67gntrjkp933s.apps.googleusercontent.com',
    iosBundleId: 'com.example.dnd',
  );
}
